export const regions = [
  {
    State: "Alaska",
    StateCode: "AK",
    Region: "West",
    Division: "Pacific",
  },
  {
    State: "Alabama",
    StateCode: "AL",
    Region: "South",
    Division: "East South Central",
  },
  {
    State: "Arkansas",
    StateCode: "AR",
    Region: "South",
    Division: "West South Central",
  },
  {
    State: "Arizona",
    StateCode: "AZ",
    Region: "West",
    Division: "Mountain",
  },
  {
    State: "California",
    StateCode: "CA",
    Region: "West",
    Division: "Pacific",
  },
  {
    State: "Colorado",
    StateCode: "CO",
    Region: "West",
    Division: "Mountain",
  },
  {
    disabled: true,
    State: "Connecticut",
    StateCode: "CT",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "District of Columbia",
    StateCode: "DC",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Delaware",
    StateCode: "DE",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Florida",
    StateCode: "FL",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Georgia",
    StateCode: "GA",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    disabled: true,
    State: "Hawaii",
    StateCode: "HI",
    Region: "West",
    Division: "Pacific",
  },
  {
    State: "Iowa",
    StateCode: "IA",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Idaho",
    StateCode: "ID",
    Region: "West",
    Division: "Mountain",
  },
  {
    State: "Illinois",
    StateCode: "IL",
    Region: "Midwest",
    Division: "East North Central",
  },
  {
    State: "Indiana",
    StateCode: "IN",
    Region: "Midwest",
    Division: "East North Central",
  },
  {
    State: "Kansas",
    StateCode: "KS",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Kentucky",
    StateCode: "KY",
    Region: "South",
    Division: "East South Central",
  },
  {
    State: "Louisiana",
    StateCode: "LA",
    Region: "South",
    Division: "West South Central",
  },
  {
    State: "Massachusetts",
    StateCode: "MA",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "Maryland",
    StateCode: "MD",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Maine",
    StateCode: "ME",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "Michigan",
    StateCode: "MI",
    Region: "Midwest",
    Division: "East North Central",
  },
  {
    State: "Minnesota",
    StateCode: "MN",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Missouri",
    StateCode: "MO",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Mississippi",
    StateCode: "MS",
    Region: "South",
    Division: "East South Central",
  },
  {
    State: "Montana",
    StateCode: "MT",
    Region: "West",
    Division: "Mountain",
  },
  {
    disabled: true,
    State: "North Carolina",
    StateCode: "NC",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "North Dakota",
    StateCode: "ND",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Nebraska",
    StateCode: "NE",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "New Hampshire",
    StateCode: "NH",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "New Jersey",
    StateCode: "NJ",
    Region: "Northeast",
    Division: "Middle Atlantic",
  },
  {
    State: "New Mexico",
    StateCode: "NM",
    Region: "West",
    Division: "Mountain",
  },
  {
    State: "Nevada",
    StateCode: "NV",
    Region: "West",
    Division: "Mountain",
  },
  {
    disabled: true,
    State: "New York",
    StateCode: "NY",
    Region: "Northeast",
    Division: "Middle Atlantic",
  },
  {
    State: "Ohio",
    StateCode: "OH",
    Region: "Midwest",
    Division: "East North Central",
  },
  {
    State: "Oklahoma",
    StateCode: "OK",
    Region: "South",
    Division: "West South Central",
  },
  {
    State: "Oregon",
    StateCode: "OR",
    Region: "West",
    Division: "Pacific",
  },
  {
    State: "Pennsylvania",
    StateCode: "PA",
    Region: "Northeast",
    Division: "Middle Atlantic",
  },
  {
    State: "Rhode Island",
    StateCode: "RI",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "South Carolina",
    StateCode: "SC",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    disabled: true,
    State: "South Dakota",
    StateCode: "SD",
    Region: "Midwest",
    Division: "West North Central",
  },
  {
    State: "Tennessee",
    StateCode: "TN",
    Region: "South",
    Division: "East South Central",
  },
  {
    disabled: true,
    State: "Texas",
    StateCode: "TX",
    Region: "South",
    Division: "West South Central",
  },
  {
    State: "Utah",
    StateCode: "UT",
    Region: "West",
    Division: "Mountain",
  },
  {
    State: "Virginia",
    StateCode: "VA",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Vermont",
    StateCode: "VT",
    Region: "Northeast",
    Division: "New England",
  },
  {
    State: "Washington",
    StateCode: "WA",
    Region: "West",
    Division: "Pacific",
  },
  {
    State: "Wisconsin",
    StateCode: "WI",
    Region: "Midwest",
    Division: "East North Central",
  },
  {
    State: "West Virginia",
    StateCode: "WV",
    Region: "South",
    Division: "South Atlantic",
  },
  {
    State: "Wyoming",
    StateCode: "WY",
    Region: "West",
    Division: "Mountain",
  },
];
