name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.name }}
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v3

      - name: check out buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Prepare Tag
        id: tag
        run: echo "name=exchange:`date +"%y.%m.%d.%H.%M"`" >> $GITHUB_OUTPUT

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ steps.tag.outputs.name }}

  alert:
    name: Alert
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ needs.build.result == 'success' }}
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"\`exchange - ${{ secrets.REGISTRY_HOST }}/${{ needs.build.outputs.tag }}\` [deployed](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) successfully :tada:\"}" $DISCORD_WEBHOOK &> /dev/null
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Failed
        if: ${{ needs.build.result != 'success' }}
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"\`exchange - ${{ secrets.REGISTRY_HOST }}/${{ needs.build.outputs.tag }}\` [deployment](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed :x:\"}" $DISCORD_WEBHOOK &> /dev/null
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
